---
abstract: 'Dist::Zilla like SHARYANTO when you build your dists'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-SHARYANTO
requires:
  App::norepeat: 0
  Dist::Zilla: 0
  Dist::Zilla::Plugin::Author::SHARYANTO::MetaResources: 0
  Dist::Zilla::Plugin::CheckChangeLog: 0
  Dist::Zilla::Plugin::CheckMetaResources: 0
  Dist::Zilla::Plugin::Extras: 0
  Dist::Zilla::Plugin::InstallRelease: 0
  Dist::Zilla::Plugin::OurPkgVersion: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::Rinci::Validate: 0.01
  Dist::Zilla::Plugin::Run: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::Plugin::Test::Compile: 2.033
  Dist::Zilla::Plugin::Test::Rinci: 0.01
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-Author-SHARYANTO
  homepage: https://metacpan.org/release/Dist-Zilla-PluginBundle-Author-SHARYANTO
  repository: git://github.com/sharyanto/perl-Dist-Zilla-PluginBundle-Author-SHARYANTO.git
version: 0.13
